### PR TITLE
Run the build as an npm project 

### LINKED ISSUE #282: Throws because of multiple versions of can-cid
Error is:

```
	throw new Error("You can't have two versions of can-cid, check your dependencies");
	^

Error: You can't have two versions of can-cid, check your dependencies
    at Object.<anonymous> (file:/Users/matthew/dev/donejs/place-my-order/node_modules/can-cid/can-cid.js:53:8)
    at file:/Users/matthew/dev/donejs/place-my-order/node_modules/can-cid/can-cid.js:58:4
    at file:/Users/matthew/dev/donejs/place-my-order/node_modules/can-cid/can-cid.js:58:98
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at doEval (/Users/matthew/dev/donejs/place-my-order/node_modules/steal-systemjs/dist/system.src.js:2059:10)
    at __eval (/Users/matthew/dev/donejs/place-my-order/node_modules/steal-systemjs/dist/system.src.js:1976:7)
    at Loader.exec [as __exec] (/Users/matthew/dev/donejs/place-my-order/node_modules/steal-systemjs/dist/system.src.js:339:5)
    at load.metadata.execute (/Users/matthew/dev/donejs/place-my-order/node_modules/steal-systemjs/dist/system.src.js:1217:16)
    at linkDynamicModule (/Users/matthew/dev/donejs/place-my-order/node_modules/steal-systemjs/dist/system.src.js:668:32)
```

### PR DESCRIPTION
**Pull request by m-mujica**
1. Give the build project a package.json with all of its deps
2. Install the dependencies in the build folder
3. Run the build

screen shot 2018-06-17 at 1 22 40 pm

Closes #282

### CODE REVIEW

**Comment by matthewp** [comment]
I imagine this fixes #282

**Comment by m-mujica** [comment]
yup. I only tried with the documentcss example in the quick start guide. Not sure what other project would be good to test this fix.

**Comment by matthewp** [comment]
Well we know the current version is totally broken so I say we release this. Awesome work!

**Comment by phillipskevin** [comment]
🙌

**Pull request merged**
